### ISSUE TITLE
Implement STOMP approach for calculating matrix profiles

### ISSUE THREAD

**Issue by aouyang1** [aouyang1/go-matrixprofile#7]
This should bring the complexity from O(n^2logn) down to O(n^2). This likely will have minimal impact on smaller timeseries

**Comment by aouyang1** [comment]
Refer to this for algorithm details https://www.cs.ucr.edu/~eamonn/STOMP_GPU_final_submission_camera_ready.pdf

**Comment by vanbenschoten** [comment]
Heads up that Z-normalizing the MASS query (as currently implemented in matrixprofile-ts) may cause STOMP to not work due to the inherent dependencies of each distance profile on the distance profile before it. I'm thinking I may need to add back in the "ComputeMeanStd" function referenced in the papers; that shouldn't be too much work, but still noteworthy.

**Comment by aouyang1** [comment]
Thanks for the heads up! I read that last night thinking that'd be the case as well. I'm going to try an implement a separate pipeline for this and then decide how/if to generalize it with STMP and STAMP.
